!function(e){if("object"==typeof exports&&"undefined"!=typeof module)module.exports=e()
else if("function"==typeof define&&define.amd)define([],e)
else{var t
t="undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:this,t.mini_blog=e()}}(function(){return function e(t,n,i){function o(r,a){if(!n[r]){if(!t[r]){var d="function"==typeof require&&require
if(!a&&d)return d(r,!0)
if(s)return s(r,!0)
var c=new Error("Cannot find module '"+r+"'")
throw c.code="MODULE_NOT_FOUND",c}var u=n[r]={exports:{}}
t[r][0].call(u.exports,function(e){var n=t[r][1][e]
return o(n?n:e)},u,u.exports,e,t,n,i)}return n[r].exports}for(var s="function"==typeof require&&require,r=0;r<i.length;r++)o(i[r])
return o}({1:[function(e,t,n){var i=e("../editor"),o=(e("../../helpers/dom"),{components:{},register:function(e,t){this.components[e]={constructor:t}},create:function(e,t){return this.components[e]?new this.components[e].constructor(t):!1},createComponent:function(e){if(!e.component&&!e.dataset.ignore){var t=e.dataset.component,n=o.create(t,e)
if(!n)return console.warn('Component "'+t+'" does not exists!')
var s=new i(null,{node:e,component:n})
n.insertEditor(s),e.component=n,e.editor=s,e.classList.add("m-anchor")}}})
t.exports=o},{"../../helpers/dom":16,"../editor":4}],2:[function(e,t,n){function i(e){this.node=e,this.initialize()}var o=(e("../../helpers/utils"),e("../../helpers/extend")),s=e("../overlay")
i.prototype={initialize:function(){},enable:function(){s.show(),this.view.activate()},disable:function(){s.hide(),this.view.deactivate()},insertEditor:function(e){this.editor=e,this.node.appendChild(e.node)},save:function(){},cancel:function(){}},i.extend=o(i),t.exports=i},{"../../helpers/extend":18,"../../helpers/utils":20,"../overlay":10}],3:[function(e,t,n){var i=e("../fields"),o=e("../../mvc/view"),s=(e("../../helpers/extend"),e("../../helpers/utils")),r=e("../../helpers/dom")
t.exports=o.extend({initialize:function(){this.fields=this.fields||{},this.nodes=this.nodes||{},this.initiateFields(this.node,this.fields),this.initiateForm(this.nodes),this.data.model.on("change",this.render.bind(this)),this.render()},initiateFields:function(e,t){var n=this
s.each(t,function(t,o){var s=t.type,a=r.find(t.target,e)
t.name=o,n.nodes[o]=new i[s](a,t)})},initiateForm:function(e){var t=this
this.form=r.node('<div class="m-hidden"></div>'),s.each(e,function(e){t.form.appendChild(e.field)}),this.node.insertBefore(this.form,this.node.children[0])},render:function(){var e=this.data.model.all()
s.each(this.nodes,function(t,n){n in e&&t.set(e[n])})},collectData:function(){var e={}
return s.each(this.nodes,function(t){e[t.name]=t.value()}),e},activate:function(){this.node.classList.add("m-editing"),this.form.classList.remove("m-hidden"),s.each(this.nodes,function(e){e.activate()})},deactivate:function(){this.node.classList.remove("m-editing"),this.form.classList.add("m-hidden"),s.each(this.nodes,function(e){e.deactivate()})}})},{"../../helpers/dom":16,"../../helpers/extend":18,"../../helpers/utils":20,"../../mvc/view":27,"../fields":6}],4:[function(e,t,n){var i=e("../mvc/view"),o=e("../helpers/dom"),s='<div class="m-editor m-dynamic"><a class="remove-button button">    <i class="fa fa-fw fa-trash"></i></a><a class="edit-button button">    <i class="fa fa-fw fa-pencil"></i></a><a class="save-button button">    <i class="fa fa-fw fa-hdd-o"></i></a></div>',r=i.extend({initialize:function(){this.node=o.node(s),this.buttons={edit:this.find(".edit-button"),save:this.find(".save-button"),remove:this.find(".remove-button")},this.setupEvents(),this.show(!0)},setupEvents:function(){this.bind(".edit-button","click",this.edit),this.bind(".save-button","click",this.save),this.bind(".remove-button","click",this.remove)},disable:function(){this.data.component.disable(),r.editing=!1,this.show(!0)},edit:function(){r.editing||(r.editing=!0,this.data.component.enable(),this.show(!1))},remove:function(){window.confirm("Are you sure you want to delete this entry?")&&(this.disable(),this.data.component.remove(),this.destroy())},save:function(){this.disable(),this.data.component.save()},destroy:function(){this.node.parentNode.removeChild(this.node)},show:function(e){this.buttons.edit.style.display=e?"":"none",this.buttons.save.style.display=e?"none":"",this.buttons.remove.style.display=e?"":"none",this.data.component.notRemovable&&(this.buttons.remove.style.display="none")}})
r.editing=!1,t.exports=r},{"../helpers/dom":16,"../mvc/view":27}],5:[function(e,t,n){var i=e("../../helpers/extend"),o=function(e,t){this.options=t,this.field=this.create(e),this.name=t.name,this.node=e,this.options.set&&(this.set=this.options.set)}
o.prototype.create=function(e){return e},o.prototype.set=function(e){this.field.value=e,this.node&&(this.node.innerHTML=e)},o.prototype.activate=function(){},o.prototype.deactivate=function(){},o.prototype.value=function(){return this.field.value},o.extend=i(o),t.exports=o},{"../../helpers/extend":18}],6:[function(e,t,n){t.exports={input:e("./input"),text:e("./text")}},{"./input":7,"./text":8}],7:[function(e,t,n){var i=e("../../helpers/dom"),o=e("./field")
t.exports=o.extend({create:function(e){var t=i.node('<input class="m-input-field m-field">')
return e&&(t.className+=" "+e.className),t},activate:function(){this.node&&this.node.classList.add("m-hidden")},deactivate:function(){this.node&&this.node.classList.remove("m-hidden")}})},{"../../helpers/dom":16,"./field":5}],8:[function(e,t,n){var i=e("../../helpers/dom"),o=e("./input")
t.exports=o.extend({create:function(e){var t=i.node('<textarea class="m-text-field m-field"></textarea>')
return e&&(t.className+=" "+e.className),t},activate:function(){o.prototype.activate.call(this),this.field.style.height=this.field.scrollHeight+6+"px"}})},{"../../helpers/dom":16,"./input":7}],9:[function(e,t,n){var i=e("./components/collection"),o=e("./settings"),s=e("../helpers/utils"),r=e("../helpers/dom")
t.exports=function(e){o.assign(e),s.toArray(r.findAll("[data-component]")).forEach(i.createComponent)}},{"../helpers/dom":16,"../helpers/utils":20,"./components/collection":1,"./settings":13}],10:[function(e,t,n){var i=e("../helpers/dom")
t.exports={element:null,show:function(){this.element||(this.element=i.node('<div class="m-hidden m-overlay"></div>'),document.body.appendChild(this.element)),this.element.classList.remove("m-hidden")},hide:function(){this.element&&this.element.classList.add("m-hidden")}}},{"../helpers/dom":16}],11:[function(e,t,n){var i=e("../components/collection"),o=e("../editor"),s=e("../../helpers/ajax"),r=e("../../mvc/view"),a=e("../../helpers/dom"),d=r.extend({initialize:function(){this.bind(".button","click",this.addView)},addView:function(e){e.preventDefault(),o.editing||this.createNode(a.find(".posts"))},createNode:function(e){if(e){var t=this,n=function(n,i){t.appendNode(i,e)}
s.post("api/template/posts").success(n).send()}},appendNode:function(e,t){var n=a.node(e.html)
n.removeAttribute("data-id"),t.insertBefore(n,t.children[0]),i.createComponent(n),n.component.post.merge(e.data),n.editor.edit()}})
t.exports=new d(a.find("#mini_panel .add"))},{"../../helpers/ajax":14,"../../helpers/dom":16,"../../mvc/view":27,"../components/collection":1,"../editor":4}],12:[function(e,t,n){e("../../helpers/utils")
t.exports={add:e("./add")}},{"../../helpers/utils":20,"./add":11}],13:[function(e,t,n){var i={settings:{},get:function(e){return this.settings[e]?this.settings[e]:null},set:function(e,t){this.settings[e]=t},assign:function(e){this.settings=e}}
t.exports=i},{}],14:[function(e,t,n){var i=e("../../core/settings"),o=e("./request"),s={}
s.request=function(e,t,n){var i=new o(this.url(e),t,n)
return i.on("data",function(e,t){"ok"===t.status?i.emit("success",e,t):i.emit("error",e,t.message)}),i.on("error",function(e,t){console.error(t)}),i},["get","post","put","delete"].forEach(function(e){var t=e.toUpperCase()
s[e]=function(e,n){return this.request(e,t,n)}}),s.url=function(e){return e=Array.isArray(e)?["",i.get("baseurl")].concat(e):["",i.get("baseurl"),e],e.join("/").replace(/\/+/,"/")},t.exports=s},{"../../core/settings":13,"./request":15}],15:[function(e,t,n){var i=e("../utils"),o=e("../events"),s=function(e,t,n){this.method=t||"GET",this.data=n||{},this.url=e,this.headers={"Content-type":"application/x-www-form-urlencoded","X-Requested-With":"XMLHttpRequest"}}
s.prototype={send:function(){var e=new XMLHttpRequest,t=this.method.toUpperCase(),n=this.query(this.data),o=this.url,s=this
"GET"===t&&n&&(o+=(-1===o.indexOf("?")?"?":"&")+n),e.open(t,o),e.onreadystatechange=function(){var t,n=this.readyState,i=this.status
if(4===n&&200===i){try{t=JSON.parse(this.responseText)}catch(o){s.emit("error",e,"Invalid JSON")}t&&s.emit("data",this,t)}},e.onerror=function(){s.emit("error",e,"Connection error")},i.each(this.headers,function(t,n){e.setRequestHeader(n,t)}),e.send(n)},success:function(e){return this.on("success",e),this},error:function(e){return this.on("error",e),this},header:function(e,t){return this.headers[e]=t,this},query:function(e){var t="",n=Object.keys(e)
return n.forEach(function(n,i){t+=encodeURIComponent(n)+"="+encodeURIComponent(e[n])+"&"}),t.substr(0,t.length-1)}},o(s.prototype),t.exports=s},{"../events":17,"../utils":20}],16:[function(e,t,n){var i={},o=document.createElement("div")
i.on=function(e,t,n){e=e||document,e.addEventListener(t,n)},i.find=function(e,t){return(t||document).querySelector(e)},i.findAll=function(e,t){return(t||document).querySelectorAll(e)},i.node=function(e){return e=e.trim(),"<"!==e[0]?document.createElement(e):(o.innerHTML=e,o.children[0])},i.insertAfter=function(e,t){e.parentNode.insertBefore(t,e.nextSibling)},t.exports=i},{}],17:[function(e,t,n){var i=function(e){e.on=function(e,t){this._events||(this._events={}),this._events[e]||(this._events[e]=[]),this._events[e].push(t)},e.emit=function(e){if(this._events&&this._events[e]){var t=mini_blog.toArray(arguments).slice(1)
this._events[e].forEach(function(e){e&&e.apply(e,t)})}}}
t.exports=i},{}],18:[function(e,t,n){var i=e("./utils"),o=function(e){return function(t){var n=function(){e.apply(this,arguments)}
return n.prototype=Object.create(e.prototype),i.each(t,function(e,t){n.prototype[t]=e}),n.extend=o(n),n}}
t.exports=o},{"./utils":20}],19:[function(e,t,n){t.exports=function(e){return e=e||(e=0),function(){return++e}}},{}],20:[function(e,t,n){var i={}
i.each=function(e,t){for(var n in e)e.hasOwnProperty(n)&&t(e[n],n)},i.diff=function(e,t){var n={}
for(var i in t)("undefined"==typeof e[i]||t[i]!==e[i])&&(n[i]=t[i]||e[i])
return n},i.merge=function(e,t){var n,i={}
for(n in e)i[n]=e[n]
for(n in t)i[n]=t[n]
return i},i.extend=function(e,t){for(var n in t)e[n]=t[n]},i.toArray=function(e){return Array.prototype.slice.call(e)},i.pick=function(e,t){var n={}
return t.forEach(function(t){e[t]&&(n[t]=e[t])}),n},t.exports=i},{}],21:[function(e,t,n){var i=e("./helpers/utils"),o={components:e("./core/components/collection"),component:e("./core/components/component"),settings:e("./core/settings"),editor:e("./core/editor"),fields:e("./core/fields"),field:e("./core/fields/field"),panel:e("./core/panel"),init:e("./core/init"),events:e("./helpers/events"),unique:e("./helpers/unique"),ajax:e("./helpers/ajax"),dom:e("./helpers/dom"),mvc:e("./mvc")}
i.extend(o,i),o.component.view=e("./core/components/view"),t.exports=o},{"./core/components/collection":1,"./core/components/component":2,"./core/components/view":3,"./core/editor":4,"./core/fields":6,"./core/fields/field":5,"./core/init":9,"./core/panel":12,"./core/settings":13,"./helpers/ajax":14,"./helpers/dom":16,"./helpers/events":17,"./helpers/unique":19,"./helpers/utils":20,"./mvc":24}],22:[function(e,t,n){var i=e("../../helpers/ajax")
t.exports={fetch:function(e,t,n,o){var s=e.options
i.get([s.baseurl,s.get,t]).success(function(t,i){var s=isNaN(n),r=e.create(e.parse(i),n)
s||(o&&o(n),e.emit("get",r))}).send()},insert:function(e,t,n){var o=e.options
i.post([o.baseurl,o.insert],t.all()).success(function(i,o){t.id=o.id,n&&n(t),e.emit("add",t)}).send()},update:function(e,t,n){var o=e.options
i.post([o.baseurl,o.update,t.id],t.diff()).success(function(){n&&n(t),e.emit("update",t)}).send()},remove:function(e,t,n){var o=e.options
i.post([o.baseurl,o.remove,t.id]).success(function(){t.destroy(),n&&n(t),e.emit("remove",t)}).send()}}},{"../../helpers/ajax":14}],23:[function(e,t,n){var i=e("../helpers/utils"),o=e("../helpers/events"),s=e("../helpers/extend"),r=e("./model"),a=function(e){this.models=e||{}}
o(a.prototype),a.prototype.get=function(e){return this.models[e]},a.prototype.add=function(e){this.models[e.id]=e,this.emit("add",e)},a.prototype.remove=function(e){var t=this.models[e]
delete this.models[e],this.emit("remove",t)},a.prototype.bootstrap=function(e){var t=this,n=function(e,n){e.id=e.id||n
var i=new r(e)
t.models[i.id]=i}
Array.isArray(e)?e.forEach(n):i.each(e,n)},a.prototype.forEach=function(e){i.each(this.models,e)},a.prototype.bindTo=function(e){var t=this.add.bind(this)
e.on("get",t),e.on("add",t),e.on("remove",this.remove.bind(this))},a.extend=s(a),t.exports=a},{"../helpers/events":17,"../helpers/extend":18,"../helpers/utils":20,"./model":26}],24:[function(e,t,n){t.exports={collection:e("./collection"),mapper:e("./mapper"),model:e("./model"),view:e("./view")}},{"./collection":23,"./mapper":25,"./model":26,"./view":27}],25:[function(e,t,n){var i=e("../helpers/events"),o=e("../helpers/extend"),s=e("../helpers/utils"),r={baseurl:"/",adapter:e("./adapters/ajax"),model:e("./model"),get:"get",insert:"add",update:"edit",remove:"remove"},a=function(e){this.options=s.merge(r,e),this.adapter=this.options.adapter}
i(a.prototype),a.prototype.parse=function(e){return e},a.prototype.create=function(e,t){return t&&t instanceof Model?(t.merge(e),t):new this.options.model(e)},a.prototype.fetch=function(e,t,n){this.adapter.fetch(this,e,t,n)},a.prototype.insert=function(e,t){this.adapter.insert(this,e,t)},a.prototype.update=function(e,t){this.adapter.update(this,e,t)},a.prototype.save=function(e,t){e.isNew()?this.insert(e,t):this.update(e,t)},a.prototype.remove=function(e,t){this.adapter.remove(this,e,t)},a.prototype.sync=function(e){e.forEach(function(t){t.isNew()?self.insert(t):t.isEmpty()?(self.remove(t),e.remove(t.id)):t.isDirty()&&self.update(t)})},a.extend=o(a),t.exports=a},{"../helpers/events":17,"../helpers/extend":18,"../helpers/utils":20,"./adapters/ajax":22,"./model":26}],26:[function(e,t,n){var i=e("../helpers/events"),o=e("../helpers/utils"),s=e("../helpers/unique")(),r=e("../helpers/extend"),a=function(e){var t=e&&e.id?e.id:-s()
e&&e.id&&delete e.id,e=o.merge(this.data||{},e||{}),this.previous=o.merge({},e),this.data=e,this.id=t}
i(a.prototype),a.prototype.get=function(e){return this.data[e]?this.data[e]:!1},a.prototype.set=function(e,t){this.data[e]=t,this.emit("change")},a.prototype.clear=function(){this.previous=o.merge({},this.data)},a.prototype.revert=function(){this.data=o.merge({},this.previous),this.emit("change")},a.prototype.all=function(){return o.merge(this.data,{})},a.prototype.diff=function(){return o.diff(this.previous,this.data)},a.prototype.destroy=function(){this.data={},this.id=-s(),this.emit("destroy")},a.prototype.reset=function(e){this.data=e,this.emit("change")},a.prototype.merge=function(e){e.id&&(this.id=e.id,delete e.id),this.data=o.merge(this.data,e),this.emit("change")},a.prototype.isNew=function(){return this.id<0},a.prototype.isDirty=function(){return Object.keys(this.diff()).length>0},a.prototype.isEmpty=function(){return 0===Object.keys(this.data).length},a.extend=r(a),t.exports=a},{"../helpers/events":17,"../helpers/extend":18,"../helpers/unique":19,"../helpers/utils":20}],27:[function(e,t,n){var i=e("../helpers/extend"),o=function(e,t){this.node=e,this.data=t,this.initialize()}
o.prototype.initialize=function(){},o.prototype.find=function(e){var t=this.node.querySelector(e)
return t||console.warn('Could not find node by selector "'+e+'"'),t},o.prototype.bind=function(e,t,n){var i=e instanceof Node?e:this.find(e)
i?i.addEventListener(t,n.bind(this)):console.warn("Node is not suitable for attaching events!")},o.extend=i(o),t.exports=o},{"../helpers/extend":18}]},{},[21])(21)})
