!function t(e,n,o){function i(r,a){if(!n[r]){if(!e[r]){var c="function"==typeof require&&require
if(!a&&c)return c(r,!0)
if(s)return s(r,!0)
var u=new Error("Cannot find module '"+r+"'")
throw u.code="MODULE_NOT_FOUND",u}var p=n[r]={exports:{}}
e[r][0].call(p.exports,function(t){var n=e[r][1][t]
return i(n?n:t)},p,p.exports,t,e,n,o)}return n[r].exports}for(var s="function"==typeof require&&require,r=0;r<o.length;r++)i(o[r])
return i}({1:[function(t,e,n){function o(t,e){this.attrubutes=t,this.node=e,this.nodes={},this.setNodes(e),this.initialize()}var i=t("../helpers/utils")
o.prototype.initialize=function(){},o.prototype.setNodes=function(t){var e=i.toArray(t.querySelectorAll("[data-name]")),n=this
Object.keys(e).forEach(function(t){var o=e[t]
n.nodes[o.getAttribute("data-name")]=o})},o.prototype.enable=function(){i.each(this.nodes,mini_blog.dom.makeEditable)},o.prototype.disable=function(){i.each(this.nodes,mini_blog.dom.unmakeEditable)},o.prototype.save=function(){},o.prototype.cancel=function(){},o.prototype.collectData=function(){var t={}
return i.each(this.nodes,function(e){t[e.getAttribute("data-name")]=e.innerHTML}),t},e.exports=o},{"../helpers/utils":13}],2:[function(t,e,n){var o=t("./editor"),i=(t("./panel"),t("../helpers/dom")),s={components:{}}
s.register=function(t,e){this.components[t]={constructor:e}},s.create=function(t,e,n){return this.components[t]?new this.components[t].constructor(e,n):!1},s.createComponent=function(t){if(!t.component&&!t.getAttribute("data-ignore")){var e=i.dataAttributes(t),n=e["data-component"],r=s.create(n,e,t)
if(!r)return console.warn('Component "'+n+'" does not exists!')
var a=new o.view(null,{component:r})
t.component=r,t.appendChild(a.node)}},e.exports=s},{"../helpers/dom":10,"./editor":3,"./panel":6}],3:[function(t,e,n){var o=t("../mvc"),i=t("./panel"),s='<div class="edit">    <button class="edit-button button">        <i class="fa fa-fw fa-pencil"></i>    </button>    <button class="remove-button button">        <i class="fa fa-fw fa-trash"></i>    </button></div><div class="editing">    <button class="save-button button">        <i class="fa fa-fw fa-floppy-o"></i>    </button>    <button class="cancel-button button">        <i class="fa fa-fw fa-times"></i>    </button></div>',r=o.view.extend({initialize:function(){this.node=document.createElement("div"),this.node.className="m-editor",this.node.innerHTML=s,this.setupEvents(),this.show(!0)},setupEvents:function(){var t=this.data.component,e=this
this.find(".edit-button").addEventListener("click",function(){t.enable(),i.enableMods(t.mods||[]),e.show(!1)}),this.find(".remove-button").addEventListener("click",function(){t.remove(),e.destroy()}),this.find(".save-button").addEventListener("click",function(){t.save(),t.disable(),i.disableMods(),e.show(!0)}),this.find(".cancel-button").addEventListener("click",function(){t.cancel(),t.disable(),i.disableMods(),e.show(!0)})},destroy:function(){this.node.parentNode.removeChild(this.node)},show:function(t){this.find(".edit").style.display=t?"block":"none",this.find(".editing").style.display=t?"none":"block",this.data.component.notRemovable&&(this.find(".remove-button").style.display="none")}})
e.exports={view:r}},{"../mvc":17,"./panel":6}],4:[function(t,e,n){var o=t("./components"),i=t("./settings"),s=t("../helpers/utils"),r=function(t){i.assign(t),s.toArray(document.querySelectorAll("[data-component]")).forEach(o.createComponent)}
e.exports=r},{"../helpers/utils":13,"./components":2,"./settings":7}],5:[function(t,e,n){function o(t){this.editor=t,this.actions={},this.init()}var i=t("../helpers/utils")
o.prototype.init=function(){},o.prototype.enable=function(){i.each(this.actions,function(t){t.button.style.display="block"})},o.prototype.disable=function(){i.each(this.actions,function(t){t.button.style.display="none"})},o.prototype.addAction=function(t,e,n){var o=document.createElement("button"),i=this
o.innerHTML=n?e:t,o.setAttribute("data-role",t),o.className="button",o.addEventListener("click",function(){i.trigger(this.getAttribute("data-role"),i.editor.current)}),this.editor.container.appendChild(o),n=n||e,n.button=o,this.actions[t]=n},o.prototype.trigger=function(t,e){this.actions[t]&&this.actions[t](e)},e.exports=o},{"../helpers/utils":13}],6:[function(t,e,n){function o(t,e){this.mods[t]=e}function i(){r.each(this.mods,function(t){t.disable()})}function s(t){r.each(this.mods,function(e){-1!==t.indexOf(e.name)&&e.enable()})}var r=t("../helpers/utils"),a={mods:{},container:document.querySelector("#mini_panel .buttons"),disableMods:i,enableMods:s,addMod:o}
e.exports=a},{"../helpers/utils":13}],7:[function(t,e,n){var o={settings:{},get:function(t){return this.settings[t]?this.settings[t]:null},set:function(t,e){this.settings[t]=e},assign:function(t){this.settings=t}}
e.exports=o},{}],8:[function(t,e,n){var o=t("../core/settings"),i={}
i.request=function(t,e,n){var o=new this.instance(this.url(t),e,n)
return o.on("data",function(t,e){"ok"!==e.status&&i.emit("error",t,e.message)}),o.on("error",function(t,e){console.log(e)}),o},["get","post","put","delete"].forEach(function(t){var e=t.toUpperCase()
i[t]=function(t,n){return this.request(t,e,n)}}),i.url=function(t){return t=Array.isArray(t)?["",o.get("baseurl")].concat(t):["",o.get("baseurl"),t],t.join("/").replace(/\/+/,"/")},i.instance=t("./ajax_instance"),e.exports=i},{"../core/settings":7,"./ajax_instance":9}],9:[function(t,e,n){var o=(t("./ajax"),t("./events")),i=function(t,e,n){this.method=e||"GET",this.data=n||{},this.url=t}
o(i.prototype),i.prototype.send=function(){var t=new XMLHttpRequest,e=this.method.toUpperCase(),n=this.query(this.data),o=this.url,i=this
"GET"===e&&n&&(o+=(-1===o.indexOf("?")?"?":"&")+n),t.open(e,o),t.onreadystatechange=function(){var e,n=this.readyState,o=this.status
if(4===n&&200===o){try{e=JSON.parse(this.responseText)}catch(s){i.emit("error",t,"Invalid JSON")}e&&i.emit("data",this,e)}},t.onerror=function(){i.emit("error",t,"AJAX Error")},t.setRequestHeader("Content-type","application/x-www-form-urlencoded"),t.setRequestHeader("X-Requested-With","XMLHttpRequest"),t.send(n)},i.prototype.success=function(t){return this.on("data",t),this},i.prototype.error=function(t){return this.on("error",t),this},i.prototype.query=function(t){var e="",n=Object.keys(t)
return n.forEach(function(n,o){e+=encodeURIComponent(n)+"="+encodeURIComponent(t[n])+"&"}),e.substr(0,e.length-1)},e.exports=i},{"./ajax":8,"./events":11}],10:[function(t,e,n){var o={}
o.attributes=function(t){for(var e={},n=t.attributes,o=0,i=n.length;i>o;o++){var s=n[o]
e[s.nodeName]=s.nodeValue}return e},o.dataAttributes=function(t){var e=mini_blog.dom.attributes(t)
return Object.keys(e).forEach(function(t){0!==t.indexOf("data-")&&delete e[t]}),e},o.makeEditable=function(t){t.setAttribute("contenteditable","true"),t.isEditable||(t.addEventListener("paste",function(t){t.preventDefault()
var e=t.clipboardData.getData("text/plain").replace(/\</g,"&lt;").replace(/\>/g,"&gt;").replace(/\n\r?/g,"<br/>\n")
document.execCommand("insertHTML",!1,e)}),t.addEventListener("keyup",function(t){13===t.keyCode&&document.execCommand("formatBlock",null,"p")}),t.isEditable=!0)},o.unmakeEditable=function(t){t.removeAttribute("contenteditable")},e.exports=o},{}],11:[function(t,e,n){var o=function(t){t.on=function(t,e){this._events||(this._events={}),this._events[t]||(this._events[t]=[]),this._events[t].push(e)},t.emit=function(t){if(this._events&&this._events[t]){var e=mini_blog.toArray(arguments).slice(1)
this._events[t].forEach(function(t){t&&t.apply(t,e)})}}}
e.exports=o},{}],12:[function(t,e,n){var o=function(t){return t=t||(t=0),function(){return++t}}
e.exports=o},{}],13:[function(t,e,n){var o=function(t,e){for(var n in t)t.hasOwnProperty(n)&&e(t[n],n)},i=function(t,e){var n={}
for(var o in e)("undefined"==typeof t[o]||e[o]!==t[o])&&(n[o]=t[o])
return n},s=function(t,e){var n,o={}
for(n in t)o[n]=t[n]
for(n in e)o[n]=e[n]
return o},r=function(t,e){for(var n in e)t[n]=e[n]},a=function(t){return Array.prototype.slice.call(t)},c=function(t,e){var n={}
return e.forEach(function(e){t[e]&&(n[e]=t[e])}),n}
e.exports={toArray:a,extend:r,merge:s,diff:i,each:o,pick:c}},{}],14:[function(t,e,n){(function(e){var n=t("./helpers/utils"),o={components:t("./core/components"),component:t("./core/component"),settings:t("./core/settings"),editor:t("./core/editor"),panel:t("./core/panel"),init:t("./core/init"),mod:t("./core/mod"),events:t("./helpers/events"),ajax:t("./helpers/ajax"),dom:t("./helpers/dom"),mvc:t("./mvc")}
n.extend(o,n),e.mini_blog=o}).call(this,"undefined"!=typeof global?global:"undefined"!=typeof self?self:"undefined"!=typeof window?window:{})},{"./core/component":1,"./core/components":2,"./core/editor":3,"./core/init":4,"./core/mod":5,"./core/panel":6,"./core/settings":7,"./helpers/ajax":8,"./helpers/dom":10,"./helpers/events":11,"./helpers/utils":13,"./mvc":17}],15:[function(t,e,n){var o=t("../helpers/utils"),i=t("../helpers/events"),s=t("./extend"),r=function(t){this.options=t,this.models={}}
i(r.prototype),r.prototype.get=function(t){return this.models[t]},r.prototype.add=function(t){this.models[t.id]=t,this.emit("add",t)},r.prototype.remove=function(t){var e=this.models[t]
delete this.models[t],this.emit("remove",e)},r.prototype.bootstrap=function(t){},r.prototype.forEach=function(t){o.each(this.models,t)},r.prototype.bindTo=function(t){var e=this
t.on("get",function(t){e.add(t)}),t.on("add",function(t){e.add(t)}),t.on("remove",function(t){e.remove(t.id)})},r.extend=s(r),e.exports=r},{"../helpers/events":11,"../helpers/utils":13,"./extend":16}],16:[function(t,e,n){var o=t("../helpers/utils"),i=function(t){return function(e){var n=function(){t.apply(this,mini_blog.toArray(arguments))}
return n.prototype=Object.create(t.prototype),o.each(e,function(t,e){n.prototype[e]=t}),n}}
e.exports=i},{"../helpers/utils":13}],17:[function(t,e,n){e.exports={collection:t("./collection"),mapper:t("./mapper"),model:t("./model"),view:t("./view")}},{"./collection":15,"./mapper":18,"./model":19,"./view":20}],18:[function(t,e,n){var o=t("../helpers/events"),i=t("../helpers/utils"),s=t("../helpers/ajax"),r=t("./extend"),a=t("./model"),c={baseurl:"/",model:a,get:"get",insert:"add",update:"edit",remove:"remove"},u=function(t){this.options=i.merge(c,t)}
o(u.prototype),u.prototype.parse=function(t){return t},u.prototype.create=function(t){return new self.options.model(t)},u.prototype.fetch=function(t,e){var n=this
s.get([this.options.baseurl,this.options.get,t]).success(function(t,e){e=n.parse(e),n.emit("get",new n.options.model(e))}).send()},u.prototype.insert=function(t){var e=this
s.post([this.options.baseurl,this.options.insert],t.all()).success(function(n,o){t.id=o.id,e.emit("add",t)}).send()},u.prototype.update=function(t){var e=this
s.post([this.options.baseurl,this.options.update,t.id],t.delta()).success(function(){e.emit("update",t)}).send()},u.prototype.remove=function(t){var e=this
s.post([this.options.baseurl,this.options.remove,t.id]).success(function(){e.emit("destroy",t)}).send()},u.prototype.sync=function(t){t.forEach(function(e){e.isNew()?self.insert(e):e.isEmpty()?(self.remove(e),t.remove(e)):e.isDirty()&&self.update(e)})},u.extend=r(u),e.exports=u},{"../helpers/ajax":8,"../helpers/events":11,"../helpers/utils":13,"./extend":16,"./model":19}],19:[function(t,e,n){var o=t("../helpers/events"),i=t("../helpers/utils"),s=t("../helpers/unique")(),r=t("./extend"),a=function(t){var e=t&&t.id?t.id:-s()
t&&t.id&&delete t.id,t=i.merge(this.data||{},t||{}),this.previous=i.merge({},t),this.data=t,this.id=e}
o(a.prototype),a.prototype.get=function(t){return this.data[t]?this.data[t]:!1},a.prototype.isNew=function(){return this.id<0},a.prototype.isDirty=function(){var t=i.diff(this.data,this.previous)
return Object.keys(t).length>0},a.prototype.isEmpty=function(){return 0===Object.keys(this.data).length},a.prototype.set=function(t,e){t&&"undefined"!=typeof e?this.data[t]=e:this.data=i.merge(this.data,t),this.emit("change")},a.prototype.clear=function(){this.previous=i.merge({},this.data)},a.prototype.revert=function(){this.data=i.merge({},this.previous),this.emit("change")},a.prototype.all=function(){return i.merge(this.data,{})},a.prototype.delta=function(){return i.diff(this.data,this.previous)},a.prototype.destroy=function(){this.data={},this.id=-1,this.emit("destroy")},a.prototype.reset=function(t){this.data=t,this.emit("change")},a.prototype.merge=function(t){t.id&&(this.id=t.id,delete t.id),this.data=i.merge(this.data,t),this.emit("change")},a.extend=r(a),e.exports=a},{"../helpers/events":11,"../helpers/unique":12,"../helpers/utils":13,"./extend":16}],20:[function(t,e,n){var o=t("./extend"),i=function(t,e){this.node=t,this.data=e,this.initialize()}
i.prototype.initialize=function(){},i.prototype.render=function(){},i.prototype.find=function(t){return this.node.querySelector(t)},i.extend=o(i),e.exports=i},{"./extend":16}]},{},[14])
